config/routes.rb
Rails.application.routes.draw do

 root to: 'homes#index'
  get 'homes/index'
  get 'homes/show'
  get 'post_books/new'
  get 'post_books/create'
  get 'post_books/index'
  get 'post_books/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bookers

  resources :post_books, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  resources :users, only: [:index,:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booker.rb
class Booker < ApplicationRecord
end

app/models/post_book.rb
class PostBook < ApplicationRecord

	validates :book_name, length: { minimum: 1 }
	validates :caption, length: { in: 1..200 }
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :profile_image

  has_many :post_books

  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction])
  end
  def after_sign_out_path_for(resource)
  homes_index_path
end
  def after_sign_in_path_for(resourse)
  	user_path(@user)
  end
    def after_sign_up_path_for(resourse)
  	user_path(@user)
  end
  def after_sign_in
  	 	flash[:notice] = "Signed in succesfully."
  end
  def after_sign_out
  	  	flash[:notice] = "Signed out succesfully."
  end
  def after_sign_up
  	flash[:notice] = "welcome! You have signed up succesfully."
  end
end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController

  def index
  	@bookers = Booker.all
  	@booker = Booker.new
  	@bookers = Booker.order("created_at asc")
  end

  def show
  	@booker = Booker.find(params[:id])
  end

  def new
  	@booker = Booker.new
  end

  def create
  	booker = Booker.new(booker_params)
  	if booker.save
  	redirect_to booker_path(booker)
  	flash[:notice] = "Book was successfully created."
  	else
  	render action: :new

  end
  end

  def edit
  	@booker = Booker.find(params[:id])
  end

  def update
  	booker = Booker.find(params[:id])
  	if booker.update(booker_params)
  	redirect_to booker_path(booker)
  	flash[:notice] = "Book was successfully updated."
  else
  	render action: :new
  end
  end

  def destroy
  	booker = Booker.find(params[:id])
  	if booker.destroy
  	redirect_to bookers_path
  	flash[:notice] = "Book was succcessfuly destroyed"
  else
  end
  end

  private

  def booker_params
  	params.require(:booker).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  	@user = User.all
  	@post_books = PostBook.all
  end

  def show
  end
end

app/controllers/post_books_controller.rb
class PostBooksController < ApplicationController
	before_action :authenticate_user!
  def new
  	@post_books = PostBook.new
  end

  def create
  	@post_book = PostBook.new(post_book_params)
  	@post_book.user_id = current_user.id
  	if @post_book.save
  	redirect_to post_book_path(@post_book.id)
  	else
  		redirect_to post_books_path
  	end
  end

  def index
  	@post_books = PostBook.all
  	@user = current_user
  	@post_book = PostBook.new

  end

  def show
  	@post_book = PostBook.find(params[:id])
  	@user = current_user
  	@post_books = PostBook.new
  end

  def edit
  	@post_book = PostBook.find(params[:id])
  	@user = User.all
  	if @post_book.user != current_user
  		redirect_to post_books_path
  	end
  end

  def update
  	post_book = PostBook.find(params[:id])
  	post_book.update(post_book_params)
  	redirect_to post_book_path
  end

  def destroy
  	post_book = PostBook.find(params[:id])
  	post_book.destroy
  	redirect_to post_books_index_path
  end

  private
      def post_book_params
        params.require(:post_book).permit(:book_name, :image, :caption, :user_id )
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def show
  	@user = User.find(params[:id])
  	@post_book = PostBook.new
  	@post_books = @user.post_books

  end

  def index
  	@users = User.all
  	@user = current_user
  	@post_book = PostBook.new

  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path
    end
  end

  def update
  	@user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
end

private

def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_books_helper.rb
module PostBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookers/edit.html.erb
<body>
	<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
	<% end %>
	<h1>Editing Book</h1>
	<%=form_for(@booker) do |f| %>
	<div class="field">
		<p>Title</p>
	<%= f.text_field :title, class: "book_title" %>
	</div>
	<div class="field">
		<p>Body</p>
	<%= f.text_area :body, class: "book_body" %>
	</div>
	<div class="action">
	<%= f.submit "Update Book" %>
	</div>
	<%= link_to "Show", booker_path(@booker), class: "show_#{@booker.id}" %> |
	<%= link_to "Back", bookers_path(@booker),class: "back" %>
	<% end %>
</body>

app/views/bookers/index.html.erb
<body>
	<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
	<% end %>
<h1>Books</h1>
<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Body</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>

<% @bookers.each do |booker| %>

	<tr>
		<td><%= booker.title %></td>
		<td><%= booker.body %></td>
		<td>
			<%= link_to "Show", booker_path(booker), class: "show_#{booker.id}" %>
		</td>
		<td>
			<%= link_to "Edit", edit_booker_path(booker), class: "edit_#{booker.id}" %>
		</td>
		<td>
			<%= link_to "Destroy", booker_path(booker),class: "destroy_#{booker.id}", method: :delete, data: {confirm: "Are you sure?"} %>
		</td>
	</tr>
<% end %>
	</tbody>

</table>

<h2>New book</h2>
<%= form_for(@booker) do |f| %>

<div class="field">
<p>Title</p>
<%= f.text_field :title, class: "book_title" %>
</div>
<div class="field">
<p>Body</p>
<%= f.text_area :body,class: "book_body" %>
</div>
<div class="action">
<%= f.submit 'Create Book'  %>
</div>



<% end %>
</body>

app/views/bookers/new.html.erb
<h1>New book</h1>
<%= form_for(@booker) do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>


<% end %>

app/views/bookers/show.html.erb
<body>
	<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<p class="show">
		<strong>Title:</strong>
		<%= @booker.title %>
	</p>
	<p class="show">
		<strong>Body:</strong>
		<%= @booker.body %>
	</p>
	<%= link_to "Edit", edit_booker_path(@booker), class: "edit_#{@booker.id}" %> |
	<%= link_to "Back", bookers_path(@booker), class: "back" %>
</body>

app/views/bookers/top.html.erb
<h1>ようこそ
<strong>Bookers</strong>
へ！
</h1>

<p class="top-text">
	<strong>Bookers</strong>
では、さまざまな書籍に関するあなたの意見や</p>
<p class="top-text">印象を共有し交換することができます</p>

<p class="top-start"><%=link_to "start",bookers_path(@booker) %></p>

app/views/homes/index.html.erb
	<%= render 'post_books/list', post_books: @post_books %>
	<br>
	<br>

		<div class="containar">
			<div class="row">
				<div class="col-xs-12 col-xs-offset-1">
					<p>
					<% flash.each do |key, value| %>
					<%= content_tag( :div, value, class: "#{key}") %>
					<% end %>
					</p>
				</div>
			</div>
		</div>
<div class="containar">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<div class="top-message col-md-offset-3 col-md-6">
				<h1 class="heading">
					Welcome to
					<span class="glyphicon glyphicon-book"><strong>Bookers</strong>
						!!
					</span>
				</h1>
				<p>
					In
					<span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,
				</p>
				<p>
					you can share and exchange your opinions , inpressions , and emotions
				</p>
				<p>about varioius books!</p>
				<div class="btn-wrapper">
					<div class="row">
						<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %>
					</div>
					<div class="row">
						<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>




<footer>
	<div class="containar">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infreatop.ink</p>
			</div>
		</div>
	</div>
</footer>

app/views/homes/show.html.erb
	<%= render 'post_books/list', post_books: @post_books %>

<div class="body">
	<div class="containar">
		<div class="row">
			<div class="col-xs-10 col-xs-offset-1">
				<h1 class="heading">
					Welcome to
					<span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>
					!
				</h1>
			</div>
		</div>
	</div>
</div>


<footer>
	<div class="containar">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infreatop.ink</p>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post_books/_list.html.erb
	<header class= "navbar navbar-fixed-top navbar-inverse">
		<div class= "containar">
			<div class="row">
				<div class="col-xs-10 col-xs-offset-1">
					<nav class= "nav navbar-nav navbar-left">
						<span>Bookers</span>
					</nav>
					<nav>
						<ul class="navbar navbar-nav navbar-right">
							<% if user_signed_in? %>
							<li>
								<%=link_to " Home", user_path(current_user),class: 'glyphicon glyphicon-home' %>
							</li>
							<li>
								<%=link_to " Users", users_path(@users),class: "glyphicon glyphicon-user" %>
							</li>
							<li>
								<%=link_to " Books", post_books_path(@post_book),class: "glyphicon glyphicon-book" %>
							</li>
							<li>
								<%= link_to " Logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out"%>
							</li>
							<% else %>
							<li>
								<%=link_to " Home", homes_index_path, class: "glyphicon glyphicon-home" %>
							</li>
							<li>
								<%=link_to " About", homes_show_path, class: "glyphicon glyphicon-user" %>
							</li>
							<li>
								<%=link_to " Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
							</li>
							<li>
								<%=link_to " Log in", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
							</li>
							<% end %>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</header>

app/views/post_books/create.html.erb
<h1>PostBooks#create</h1>
<p>Find me in app/views/post_books/create.html.erb</p>

app/views/post_books/edit.html.erb
	<%= render 'post_books/list', post_books: @post_books %>
	<br>
	<br>


<div class="body">
	<div class="containar">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<h1 class="heading">Editing Book</h1>
				<%=form_for(@post_book) do |f| %>
				<div class="field row">
					<label for="book_name">Title</label>
					<%= f.text_field :book_name, class: "col-xs-12" %>
					<br>
					<br>
					<br>
				</div>
				<div class="field row">
					<label for="caption">Opinion</label>
					<%= f.text_area :caption, class: "col-xs-12"%>
					<br>
					<br>
					<br>
					<br>
				</div>
				<div class="action row">
					<%= f.submit "Update Book", class: "col-xs-12 btn btn-primary" %>
				</div>
				<% end %>
				<br>
				<%=link_to "Show", post_book_path(@post_book) %> |
				<%=link_to "back", post_books_path(@post_book) %>
			</div>
		</div>
	</div>
</div>

<footer>
	<div class="containar">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infreatop.ink</p>
			</div>
		</div>
	</div>
</footer>

app/views/post_books/index.html.erb
<body>
	<%= render 'post_books/list', post_books: @post_books %>

	<div class="body">
		<div class="containar">
			<div class="row">
				<div class="col-xs-2 col-xs-offset-1">
					<h2 class="heading">Users info</h2>
					<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
					<table class= "table">
						<tbody>
							<tr></tr>
							<tr>
							<th>name</th>
							<th><%= @user.name %></th>
							</tr>
							<tr>
							<th>intoroduction</th>
							<th><%= @user.introduction %></th>
							</tr>
						</tbody>
					</table>
					<div class="row">
						<% if @user.id == current_user.id %>
							<%= link_to "", edit_user_path(@user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
						<% end %>
					</div>


					<h2>New book</h2>
					<%= form_for(@post_book) do |f| %>
						<div class="field row">
							<label for="book_name">Title</label>
							<%= f.text_field :book_name, class: "col-xs-12" %>
							<span class="fa fa-building form-control-icon" aria-hidden="true"></span>
						</div>
						<br>
					<div class="field row">
						<label for="caption">Opinion</label>
							<%= f.text_area :caption, class: "col-xs-12" %>
					</div>
					<br>
					<br>
					<div class="action row">
						<%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
					</div>
					<% end %>
				</div>


				<div class="col-xs-8">
					<h2 class="heading">Books</h2>
						<table class="table table-hover table-inverse">
							<thead>
								<tr>
									<th></th>
									<th>Title</th>
									<th>Opinion</th>
									<th colspan="3"></th>
								</tr>
							</thead>
							<% @post_books.each do |post_book| %>
							<tbody>
								<tr>
									<td><%= attachment_image_tag post_book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "", fallback: "no_image.jpg", :size => "40x40" %></td>
									<td><%= link_to post_book_path(post_book.id) do %>
											<%= post_book.book_name %>
										<% end %>
									</td>
									<td><%= post_book.caption %></td>
								</tr>
							<% end %>
							</tbody>
						</table>
				</div>
			</div>
		</div>
	</div>



<footer>
	<div class="containar">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infreatop.ink</p>
			</div>
		</div>
	</div>
</footer>

app/views/post_books/new.html.erb
<h1>New book</h1>


<h4>Title</h4>


<h4>Body</h4>

 					<h2>New book</h2>
						<%= form_for(@post_book) do |f| %>
							<div class="field row">
								<label for="book_name">Title</label>
									<%= f.text_field :book_name, class: "col-xs-12" %>
										<span class="fa fa-building form-control-icon" aria-hidden="true"></span>
							</div>
							<br>
							<div class="field row">
								<label for="caption">Opinion</label>
									<%= f.text_area :caption, class: "col-xs-12" %>
							</div>
							<br>
							<br>
							<div class="action row">
								<%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
							</div>
						<% end %>
				</div>

app/views/post_books/show.html.erb
	<%= render 'post_books/list', post_books: @post_books %>

	<div class="body">
		<div class="containar">
			<div class="row">
				<div class="col-xs-2 col-xs-offset-1">
					<h2 class="heading">Users info</h2>
						<%= attachment_image_tag @post_book.user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
						<table class= "table">
							<tbody>
								<tr></tr>
								<tr>
									<th>name</th>
									<th><%= @post_book.user.name %></th>
								</tr>
								<tr>
									<th>intoroduction</th>
									<th><%= @post_book.user.introduction %></th>
								</tr>
							</tbody>
						</table>
					<div class="row">
						<% if @post_book.user.id == current_user.id %>
							<%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
						<% end %>
					</div>



					<h2>New book</h2>
						<%= form_for(@post_books) do |f| %>
							<div class="field row">
								<label for="book_name">Title</label>
									<%= f.text_field :book_name, class: "col-xs-12" %>
										<span class="fa fa-building form-control-icon" aria-hidden="true"></span>
							</div>
							<br>
							<div class="field row">
								<label for="caption">Opinion</label>
									<%= f.text_area :caption, class: "col-xs-12" %>
							</div>
							<br>
							<br>

							<div class="action row">
								<%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
							</div>
						<% end %>
				</div>



				<div class="col-xs-8">
					<h2 class="heading">Book detail</h2>
						<table class="table">
							<tbody>
								<tr>
									<td>
										<%= attachment_image_tag @post_book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "", fallback: "no_image.jpg", :size => "40x40" %>
										<br>
										<%= link_to user_path(@post_book.user) do %>
										<%= @post_book.user.name %>
										<% end %>
									</td>
									<td><%= @post_book.book_name %></td>
									<td><%= @post_book.caption %></td>
									<% if @post_book.user == current_user %>
									<td><%= link_to "Edit", edit_post_book_path(@post_book), class: "btn-sm btn-success" %></td>
									<td></td>
									<td><%= link_to "Destroy", post_book_path(@post_book), method: :delete, class: "btn-sm btn-danger", data: {confirm: "本当に消しますか？"} %></td>
									<% end %>
								</tr>
							</tbody>
						</table>
				</div>
			</div>
		</div>
	</div>



<footer>
	<div class="containar">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infreatop.ink</p>
			</div>
		</div>
	</div>
</footer>

app/views/users/edit.html.erb
	<%= render 'post_books/list', post_books: @post_books %>

	<div class="body">
		<div class="containar">
			<div class="row">
				<div class="col-xs-3 col-xs-offset-1">
					<h2 class="heading">User info</h2>
					<%= form_for(@user) do |f| %>
					<div class="field">
						<label for="book_name">Name</label>
						<%= f.text_field :name %>
					</div>
					<br>
					<div class="field">
						<label for="user_image">Image</label>
						<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
					</div>
					<br>
					<div class="field">
						<label for="caption">Introduction</label>
						<%= f.text_field :introduction %>
					</div>
					<br>
					<div class="action">
					<%= f.submit "Update User" %>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>


<footer>
	<div class="containar">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infreatop.ink</p>
			</div>
		</div>
	</div>
</footer>

app/views/users/index.html.erb
	<%= render 'post_books/list', post_books: @post_books %>

	<div class="body">
		<div class="containar">
			<div class="row">
				<div class="col-xs-2 col-xs-offset-1">
					<h2 class="heading">Users info</h2>
						<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
						<table class= "table">
							<tbody>
								<tr></tr>
								<tr>
									<th>name</th>
									<th><%= @user.name %></th>
								</tr>
								<tr>
									<th>intoroduction</th>
									<th><%= @user.introduction %></th>
								</tr>
							</tbody>
						</table>
					<div class="row">
						<% if @user.id == current_user.id %>
							<%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
						<% end %>
					</div>



					<h2>New book</h2>
						<%= form_for(@post_book) do |f| %>
							<div class="field row">
								<label for="book_name">Title</label>
									<%= f.text_field :book_name, class: "col-xs-12" %>
										<span class="fa fa-building form-control-icon" aria-hidden="true"></span>
							</div>
							<br>
							<div class="field row">
								<label for="caption">Opinion</label>
									<%= f.text_area :caption, class: "col-xs-12" %>
							</div>
							<br>
							<br>
							<div class="action row">
								<%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
							</div>
						<% end %>
				</div>


				<div class="col-xs-8">
					<h2 class="heading">Users</h2>
						<table class="table table-hover table-inverse">
							<thead>
								<tr>
									<th>image</th>
									<th>name</th>
									<th colspan="3">Option</th>
								</tr>
							</thead>
							<tbody>
								<% @users.each do |user| %>
									<tr>
										<td>
										<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "", fallback: "no_image.jpg", :size => "40x40" %>
										</td>
										<td><%= user.name %></td>
										<td>
											<a><%=link_to "Show",user_path(user[:id]) %></a>
										</td>
									</tr>
								<% end %>
							</tbody>
						</table>
				</div>
			</div>
		</div>
	</div>

<footer>
	<div class="containar">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infreatop.ink</p>
			</div>
		</div>
	</div>
</footer>

app/views/users/show.html.erb
	<%= render 'post_books/list', post_books: @post_books %>
<br>
<br>

<div class="containar">
	<div class="row">
		<div class="col-xs-11 col-xs-offset-1">
			<p>
				<% flash.each do |key, value| %>
					<%= content_tag( :div, value, class: "#{key}") %>
				<% end %>
			</p>
		</div>
	</div>
</div>

	<div class="body">
		<div class="containar">
			<div class="row">
				<div class="col-xs-2 col-xs-offset-1">
					<h2>Users info</h2>
						<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
							<table class= "table">
								<tbody>
									<tr></tr>
									<tr>
										<th>name</th>
										<th><%= @user.name %></th>
									</tr>
									<tr>
										<th>intoroduction</th>
										<th><%= @user.introduction %></th>
									</tr>
								</tbody>
							</table>
					<div class="row">
						<% if @user.id == current_user.id %>
							<a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" <%= link_to "", edit_user_path(@user) %></a>
						<% end %>
					</div>



					<h2>New book</h2>
						<%= form_for(@post_book) do |f| %>
							<div class="field row">
								<label for="book_name">Title</label>
									<%= f.text_field :book_name, class: "col-xs-12" %>
									<span class="fa fa-building form-control-icon" aria-hidden="true"></span>
							</div>
							<br>
							<div class="field row">
								<label for="caption">Opinion</label>
									<%= f.text_area :caption, class: "col-xs-12" %>
							</div>
							<br>
							<br>

							<div class="action row">
								<%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
							</div>
						<% end %>
				</div>


				<div class="col-xs-8">
					<h2>Books</h2>
						<table class="table table-hover table-inverse">
							<thead>
								<tr>
									<th></th>
									<th>title</th>
									<th colspan="3">Option</th>
								</tr>
							</thead>
							<tbody>
							<% @post_books.each do |post_book| %>
								<tr>
									<td>
										<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "", fallback: "no_image.jpg", :size => "40x40" %>
									</td>
									<td><%= link_to post_book_path(post_book.id) do %>
											<%= post_book.book_name %>
										<% end %>
									</td>
									<td><%= post_book.caption %></td>
								</tr>
							<% end %>
							</tbody>
						</table>
				</div>
			</div>
		</div>
	</div>


<footer>
	<div class="containar">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infreatop.ink</p>
			</div>
		</div>
	</div>
</footer>